-------------------- PHANTOM READS --------------------

-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ -- phantom reads
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE -- solution phantom reads
BEGIN TRAN
SELECT * FROM Legume
WAITFOR DELAY '00:00:05'
SELECT * FROM Legume
COMMIT TRAN