SET TRANSACTION ISOLATION LEVEL REPEATABLE READ -- phantom reads
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE -- solution phantom reads
BEGIN TRAN
SELECT * FROM Categories
WAITFOR DELAY '00:00:05'
SELECT * FROM Categories
COMMIT TRAN