package rpcprotocol;


public enum RequestType {
    LOGIN, LOGOUT, CAUTA_USERNAME, NR_PARTICIPANTI_PROBA, LISTA_PROBE, LISTA_PARTICIPANTI,
    LISTA_CATEGORII, LISTA_PROBE_NUME, LISTA_PROBE_DTO, LISTA_PARTICIPANTI_FILTRATI, INSCRIERE_NOUA;
}
