package rpcprotocol;


public enum ResponseType {
    OK, ERROR, INSCRIERE_NOUA, GET_USER, GET_NR_PARTICIPANTI_PROBA, GET_LISTA_PROBE, GET_LISTA_PARTICIPANTI,
    GET_LISTA_CATEGORII, GET_LISTA_PROBE_NUME, GET_LISTA_PROBE_DTO, GET_LISTA_PARTICIPANTI_FILTRATI, UPDATE;
}
