/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.teofana.concurs;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-04")
public class Participant implements org.apache.thrift.TBase<Participant, Participant._Fields>, java.io.Serializable, Cloneable, Comparable<Participant> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Participant");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField NUME_FIELD_DESC = new org.apache.thrift.protocol.TField("nume", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField VARSTA_FIELD_DESC = new org.apache.thrift.protocol.TField("varsta", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ParticipantStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ParticipantTupleSchemeFactory();

  public int id; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String nume; // required
  public int varsta; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    NUME((short)2, "nume"),
    VARSTA((short)3, "varsta");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // NUME
          return NUME;
        case 3: // VARSTA
          return VARSTA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __VARSTA_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NUME, new org.apache.thrift.meta_data.FieldMetaData("nume", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VARSTA, new org.apache.thrift.meta_data.FieldMetaData("varsta", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Participant.class, metaDataMap);
  }

  public Participant() {
  }

  public Participant(
    int id,
    java.lang.String nume,
    int varsta)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.nume = nume;
    this.varsta = varsta;
    setVarstaIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Participant(Participant other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetNume()) {
      this.nume = other.nume;
    }
    this.varsta = other.varsta;
  }

  public Participant deepCopy() {
    return new Participant(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.nume = null;
    setVarstaIsSet(false);
    this.varsta = 0;
  }

  public int getId() {
    return this.id;
  }

  public Participant setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getNume() {
    return this.nume;
  }

  public Participant setNume(@org.apache.thrift.annotation.Nullable java.lang.String nume) {
    this.nume = nume;
    return this;
  }

  public void unsetNume() {
    this.nume = null;
  }

  /** Returns true if field nume is set (has been assigned a value) and false otherwise */
  public boolean isSetNume() {
    return this.nume != null;
  }

  public void setNumeIsSet(boolean value) {
    if (!value) {
      this.nume = null;
    }
  }

  public int getVarsta() {
    return this.varsta;
  }

  public Participant setVarsta(int varsta) {
    this.varsta = varsta;
    setVarstaIsSet(true);
    return this;
  }

  public void unsetVarsta() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VARSTA_ISSET_ID);
  }

  /** Returns true if field varsta is set (has been assigned a value) and false otherwise */
  public boolean isSetVarsta() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VARSTA_ISSET_ID);
  }

  public void setVarstaIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VARSTA_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Integer)value);
      }
      break;

    case NUME:
      if (value == null) {
        unsetNume();
      } else {
        setNume((java.lang.String)value);
      }
      break;

    case VARSTA:
      if (value == null) {
        unsetVarsta();
      } else {
        setVarsta((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case NUME:
      return getNume();

    case VARSTA:
      return getVarsta();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case NUME:
      return isSetNume();
    case VARSTA:
      return isSetVarsta();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Participant)
      return this.equals((Participant)that);
    return false;
  }

  public boolean equals(Participant that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_nume = true && this.isSetNume();
    boolean that_present_nume = true && that.isSetNume();
    if (this_present_nume || that_present_nume) {
      if (!(this_present_nume && that_present_nume))
        return false;
      if (!this.nume.equals(that.nume))
        return false;
    }

    boolean this_present_varsta = true;
    boolean that_present_varsta = true;
    if (this_present_varsta || that_present_varsta) {
      if (!(this_present_varsta && that_present_varsta))
        return false;
      if (this.varsta != that.varsta)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + ((isSetNume()) ? 131071 : 524287);
    if (isSetNume())
      hashCode = hashCode * 8191 + nume.hashCode();

    hashCode = hashCode * 8191 + varsta;

    return hashCode;
  }

  @Override
  public int compareTo(Participant other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNume()).compareTo(other.isSetNume());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNume()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nume, other.nume);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetVarsta()).compareTo(other.isSetVarsta());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVarsta()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.varsta, other.varsta);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Participant(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("nume:");
    if (this.nume == null) {
      sb.append("null");
    } else {
      sb.append(this.nume);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("varsta:");
    sb.append(this.varsta);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ParticipantStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ParticipantStandardScheme getScheme() {
      return new ParticipantStandardScheme();
    }
  }

  private static class ParticipantStandardScheme extends org.apache.thrift.scheme.StandardScheme<Participant> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Participant struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NUME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.nume = iprot.readString();
              struct.setNumeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // VARSTA
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.varsta = iprot.readI32();
              struct.setVarstaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Participant struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      if (struct.nume != null) {
        oprot.writeFieldBegin(NUME_FIELD_DESC);
        oprot.writeString(struct.nume);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(VARSTA_FIELD_DESC);
      oprot.writeI32(struct.varsta);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ParticipantTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ParticipantTupleScheme getScheme() {
      return new ParticipantTupleScheme();
    }
  }

  private static class ParticipantTupleScheme extends org.apache.thrift.scheme.TupleScheme<Participant> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Participant struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetNume()) {
        optionals.set(1);
      }
      if (struct.isSetVarsta()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetNume()) {
        oprot.writeString(struct.nume);
      }
      if (struct.isSetVarsta()) {
        oprot.writeI32(struct.varsta);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Participant struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.nume = iprot.readString();
        struct.setNumeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.varsta = iprot.readI32();
        struct.setVarstaIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

