/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.teofana.concurs;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-06")
public enum TipUser implements org.apache.thrift.TEnum {
  ADMIN(1),
  OPERATOR(2);

  private final int value;

  private TipUser(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TipUser findByValue(int value) { 
    switch (value) {
      case 1:
        return ADMIN;
      case 2:
        return OPERATOR;
      default:
        return null;
    }
  }
}
