/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Concurs
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Participant : TBase
  {
    private int _id;
    private string _nume;
    private int _varsta;

    public int Id
    {
      get
      {
        return _id;
      }
      set
      {
        __isset.id = true;
        this._id = value;
      }
    }

    public string Nume
    {
      get
      {
        return _nume;
      }
      set
      {
        __isset.nume = true;
        this._nume = value;
      }
    }

    public int Varsta
    {
      get
      {
        return _varsta;
      }
      set
      {
        __isset.varsta = true;
        this._varsta = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool id;
      public bool nume;
      public bool varsta;
    }

    public Participant() {
    }

        public Participant(string nume, int varsta)
        {
            __isset.nume = true;
            this._nume = nume;

            __isset.varsta = true;
            this._varsta = varsta;
        }
        public Participant(int id, string nume, int varsta)
    {
        __isset.id = true;
        this._id = id;

        __isset.nume = true;
        this._nume = nume;

        __isset.varsta = true;
        this._varsta = varsta;
    }

        public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                Id = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Nume = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                Varsta = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Participant");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.id) {
          field.Name = "id";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Id);
          oprot.WriteFieldEnd();
        }
        if (Nume != null && __isset.nume) {
          field.Name = "nume";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Nume);
          oprot.WriteFieldEnd();
        }
        if (__isset.varsta) {
          field.Name = "varsta";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Varsta);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Participant(");
      bool __first = true;
      if (__isset.id) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Id: ");
        __sb.Append(Id);
      }
      if (Nume != null && __isset.nume) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Nume: ");
        __sb.Append(Nume);
      }
      if (__isset.varsta) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Varsta: ");
        __sb.Append(Varsta);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
