/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Concurs
{
  public enum TipUser
  {
    ADMIN = 1,
    OPERATOR = 2,
  }
}
